AY2324S2-CS2103T-T09-2/tp

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/orders/AddOrderCommand.java, src/main/java/seedu/address/logic/commands/orders/DeleteOrderCommand.java, src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/order/Order.java, src/main/java/seedu/address/model/order/OrderId.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/storage/JsonAdaptedOrder.java, src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java, src/test/java/seedu/address/logic/commands/clients/AddCommandTest.java, src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
Stores all Orders under Person class as a Set, resolves #50
=> Implement View, Create and Delete Order commands to ModelManager

docs/diagrams/StorageClassDiagram.puml, src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/orders/AddOrderCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ReadOnlyAddressBook.java, src/main/java/seedu/address/model/order/OrderId.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedOrder.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/OrderCard.java, src/main/java/seedu/address/ui/OrderListPanel.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/OrderListCard.fxml, src/main/resources/view/OrderListPanel.fxml, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java, src/test/java/seedu/address/logic/commands/clients/AddCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
Current error I have face I run the Application is "Cannot invoke javafx.scene.control.ListView.setltems(javafx.collections.ObservableList) because "this.orderListView" is null
=> Update UI classes to show Order List alongside Client List

src/main/java/seedu/address/model/order/Order.java
=> Add non null requirement for Order

docs/DeveloperGuide.md
Reformatted some lines
Improved elaboration for the `DeleteOrderCommand` class.
Added lines for `EditOrderCommand` class.
=> Update DG for EditOrderCommand

src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/util/SampleDataUtil.java
Fixes #107 
Currently, the OrderPanel in the GUI does not update when persons are
deleted.
This commit fixes it such that the orders belonging to deleted persons
will be deleted as well and updated in the GUI.
This PR also adds back more sample persons in SampleDataUtil.java to allow easier testing without needing to
manually adding new persons
=> Update GUI updating when person is deleted

docs/UserGuide.md
The UserGuide is not up to date with our latest implementations.
This may confuse the user when going through the UserGuide.
Update the UserGuide with our new features.
This will ensure the User will have the knowledge to use these respective commands.
=> Update the UserGuide

src/main/java/seedu/address/logic/commands/orders/AddOrderCommand.java, src/main/java/seedu/address/model/order/Deadline.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/resources/view/DarkTheme.css, src/test/java/seedu/address/model/order/DeadlineTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java
When the list is empty, the background color will reset to white, the
default color.
This is ugly and not the intended outcome of our application.
Add a default color for background when the list is empty.
This is more pleasant to the user's eyes, and will allow our
application to look better.
=> Add Background Color when empty

docs/UserGuide.md
The UserGuide is out of date.
The users might not be able to correctly execute certain commands.
Edit the UserGuide.
The users will have a more accurate guide to follow.
=> Edit the UserGuide

src/main/java/seedu/address/logic/commands/orders/AddOrderCommand.java, src/main/java/seedu/address/logic/commands/orders/EditOrderCommand.java, src/main/java/seedu/address/model/order/Status.java
isBlank is a superset of isEmpty
EditOrderCommand.MESSAGE_NOT_EDITED is unused
=> Remove unused code

.github/workflows/gradle.yml
Codecov is not working for PRs.
This is an attempt to fix.
=> Change gradle.yml for PR codecov

docs/UserGuide.md, src/main/java/seedu/address/model/tag/Tag.java
=> Updating the edit command error message

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/ModelManager.java
The logger information is outputing the wrong message.
Fix the logger information to keep up to date with our 
application name.
Resolves #173
=> Fix misleading logger information

src/main/java/seedu/address/logic/parser/ParserUtil.java
Reverts AY2324S2-CS2103T-T09-2/tp#214
=> Revert #214

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
=> Fix date issues causing app to fail

src/main/java/seedu/address/ui/OrderCard.java, src/main/resources/view/OrderListCard.fxml
Resolves #239
Removed OrderId from OrderListCard
=> Remove OrderId from UI

docs/UserGuide.md
Documents in UG that deadlines can be set before today.
Fixes #165
=> Document that Deadline allowed before today

docs/UserGuide.md
Added constraints on numerical sizes, filtering orders, intuitive error messaging
Data types and length may potentially go into command constraints rather
than feature enhancements, because tags or numbers of that size are
simply unrealistic and there is no real need to handle them outside of
security reasons.
Resolves #230 
Resolves #172
=> Update planned enhancements

src/main/java/seedu/address/logic/parser/order/AddOrderCommandParser.java, src/main/java/seedu/address/model/order/Price.java, src/main/java/seedu/address/model/order/Remark.java, src/test/java/seedu/address/model/order/PriceTest.java
Missing parameters will not cause an error to appear.
Fix the code to ensure that it will come out.
Resolves #170
=> Fix AddOrderCommandParser bugs

src/main/java/seedu/address/logic/commands/order/EditOrderCommand.java, src/main/java/seedu/address/model/client/Client.java
Move Client specific code to Client class.
=> Fix weak SLAP in EditOrderCommand

docs/UserGuide.md
Parts that are unclear have been edited and redundant information has been removed.
=> Update UserGuide.md to remove unnecessary parts
